In [1]:
import numpy as np

In [8]:
num_to_check = 125
n,m = 5,5
for i in range(num_to_check):
    print(np.array([int(k) for k in "{0:b}".format(i).zfill(n * m)]).reshape(n, m))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 1 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 1 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 0 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 0]]
[[0 0 0 0 

In [17]:
def arg_sort_rows(matrix):
    spliced_matrix = np.flipud(matrix.T) # np.rot90(matrix) #np.flipud(matrix.T)
    return np.lexsort(spliced_matrix)

In [46]:
def arg_sort_rows_1(matrix):
    spliced_matrix = [matrix[:, i] for i in range(matrix.shape[1])]
    spliced_matrix.reverse()
    sorted_indecis = np.lexsort(spliced_matrix)
    return np.flip(sorted_indecis)

In [72]:
sizes=4
matrix = np.random.randint(4, size=(sizes, sizes))
matrix

array([[1, 1, 3, 0],
       [2, 2, 1, 1],
       [1, 3, 0, 0],
       [0, 3, 3, 3]])

In [73]:
expected_result = np.array([1,2,0,3])

In [74]:
arg_sort_rows_1(matrix)

array([1, 2, 0, 3], dtype=int64)

In [13]:
t1 = np.random.rand(2,1)
t1

array([[0.71970844],
       [0.31214417]])

In [14]:
t2 = np.random.rand(2,1)
t2

array([[0.6645377 ],
       [0.66292803]])

In [15]:
t3 = np.random.rand(2,2)
t3

array([[0.9605482 , 0.96754915],
       [0.27933032, 0.87540845]])

In [33]:
t4 = np.concatenate((t2,t1), 1)
t4

array([[0.6645377 , 0.71970844],
       [0.66292803, 0.31214417]])

In [23]:
t4.argsort()

array([[0, 1],
       [1, 0]], dtype=int64)

In [37]:
row_order_indices = np.argsort(t4, axis=1)
row_order_indices

array([[0, 1],
       [1, 0]], dtype=int64)

In [41]:
t4[0].argsort()

array([0, 1], dtype=int64)

In [32]:
sorted_row_order = t4[:, 0]
sorted_row_order

array([0.6645377 , 0.66292803])

In [40]:
array = np.array([[3, 2, 5],
                  [1, 4, 6],
                  [7, 0, 2]])
array = t4
# Get the row order indices
row_order_indices = np.argsort(array[:, 0], axis=1)

# Create a 1-D array with the new row order
sorted_row_order = row_order_indices#[:, 0]

print(sorted_row_order)

AxisError: axis 1 is out of bounds for array of dimension 1

In [38]:
array = np.array([[3, 2, 5],
                  [1, 4, 6],
                  [7, 0, 2]])

# Get the row order indices
row_order_indices = np.argsort(array, axis=1)

# Create a 1-D array with the new row order
sorted_row_order = row_order_indices[:, 0]

print(sorted_row_order)

[1 0 1]


In [42]:
def func_1(n):
    return n*(n+1) -n

In [ ]:
def func_2(n):
    return

In [80]:
import math
def true_func(n):
    cur_sum = 0
    for i in range(1,n+1):
        exp_part = 2**(n-i)
        exp_amt = 2*(i-1) + 1
        cur_i = exp_part * exp_amt
        cur_sum += cur_i
        print(f"exp: {exp_part} amt: {exp_amt} full: {cur_i}")
    return cur_sum

In [112]:
import math
def pred_func(n):
    cur_sum = 0
    for i in range(1,n+1):
        exp_part = 2**(n-i+1) * (i-1)
        exp_amt = 2**(n-i)
        cur_i =  exp_part + exp_amt
        cur_sum += cur_i
        print(f"exp: {exp_part} amt: {exp_amt} full: {cur_i}")
    return cur_sum

In [172]:
import math
def pred_func(n):
    cur_sum = 0
    for i in range(1,n+1):
        cur_i =  2**(n-i+1)*(i - .5)
        cur_sum += cur_i
        print(f"exp: {exp_part} amt: {exp_amt} full: {cur_i}")
    return cur_sum

In [200]:
#the number of possible matrices?
def pred_func(n):
    cur_sum = 0
    for i in range(1,n+1):
        cur_i = 2**(n-i) * (2*i-1)
        cur_sum += cur_i
        print(f"exp:  amt:  full: {cur_i}")
    return cur_sum

In [ ]:
def pred_func(n):
    cur_sum = 0
    for i in range(1, n + 1):
        cur_i = 2 ** (n - i) * (2 * i - 1)
        cur_sum += cur_i
        #print(f"exp:  amt:  full: {cur_i}")
    return cur_sum

In [222]:
import math
def pred_func(n):
    m = n - ()
    return ((n-1)* (2**(n - 1)) + 2) - (2**n)

In [223]:
true_func(4)

exp: 8 amt: 1 full: 8
exp: 4 amt: 3 full: 12
exp: 2 amt: 5 full: 10
exp: 1 amt: 7 full: 7


37

In [224]:
pred_func(4)

6130

In [214]:
2**3

8